---
title: "Figure_generator"
author: "LD"
date: "2023-05-25"
output: 
  html_document:
    keep_md: yes
---
##Advanced.rmd
```{r setup, include=FALSE}
##you will need to replace where the rds is reading from to your local environment I was having trouble with setwd()
knitr::opts_chunk$set(dev = "png",
                      dpi = 300,
                      echo = FALSE,
                      message=FALSE)

```

```{r pressure, include=FALSE}
library(tidyr)
library(dplyr)
library(bbsBayes2)
library(ggplot2)
library(bayesplot)
library(sf)
```

```{r conv,include=FALSE}
library(bayesplot)

#load our Hepatic Tanager model
mod<-readRDS("C:\\Users\\DalyL\\Downloads\\HETA_latlong_gam.rds")

#OR create a quick model for yourself, with less runs and chains
# mod<-stratify(by="bbs_cws",species="Hepatic Tanager")%>%
#   prepare_data()%>%
#   prepare_model(model_variant = "hier",model = "gam")%>%
#   run_model(chains=2, iter_warmup = 10, iter_sampling = 10)


#visually check convergence
#create an array of mcmc runs
post<-as.array(mod$model_fit$draws())

##see model parameters
get_model_vars(mod)
```
#create density plots for any parameters, coloured by chain number
```{r mcmc_density, fig.path= "./"}

mcmc_dens_overlay(post,pars=c("STRATA","phi","retrans_obs","eta","nu","sdste"))

```

```{r indices, include=FALSE}
indices <- generate_indices(mod,
                            regions = c("continent","stratum"))          #also"country","prov_state","bcr","bcr_by_country"
#plot the indices
p<-plot_indices(indices)
pp<-patchwork::wrap_plots(p, ncol = 3)&theme(axis.title.y = element_blank())

gt<-patchwork::patchworkGrob(pp)
trends<-generate_trends(indices)
```

```{r plot_indices, fig.path= "./", fig.width = 16, fig.asp = length(plot)/3*3}

gridExtra::grid.arrange(gt,left="Annual index of abundance /n (mean count)")
```


```{r HETA_cont, fig.path= "./"}
p[[1]]
```

```{r HETA_103, fig.path= "./"}
p[[2]]
```

```{r HETA_trend, fig.path= "./"}
plot_map(trends, col_viridis = FALSE)
```

```{r, include = FALSE}
#load a model with prov_state in the regions to geofacet trajectories
#read the RDS file from bbsBayes2 github
library(readr)
bars <- read_rds(unzip(
  "C:\\Users\\DalyL\\Downloads\\BARS_spatial_gamye.zip",
  "BARS_spatial_gamye.rds"))

indices<-generate_indices(bars,regions=c("prov_state","country","stratum"))
trends<-generate_trends(indices)
gf <- plot_geofacet(indices=indices,
                    trends = trends,
                    multiple = TRUE,
                    slope = FALSE)
```

```{r BARS_geofacet, fig.path= "./"}
print (gf)
```

```{r, include=FALSE}
#a quick slope model, for a 10 year period
strat<- stratify(by="bbs_usgs",species="Hepatic Tanager")

data<- prepare_data(strat,min_year=2009, max_year= 2019)
prep<- prepare_model(data,model = "slope",use_pois = TRUE)
  #for prepare_model must be "slope" and use_pois=TRUE

#quick model, we recommend using the defaults, 4 chains, 1000 iterations for both warmup #and sampling, and assessing convergence
slope_mod<-run_model(
  prep,chains=2,iter_warmup = 500,iter_sampling =100,save_model = FALSE)


slope_ind <- generate_indices(
  model_output = slope_mod,regions = c("continent")) 
                              

slope_plot<-plot_indices(indices = slope_ind,
                          add_observed_means = TRUE)
```

```{r HETA_slope, fig.path="./"}
slope_plot[[1]]
```

``` {r, include=FALSE}
stratified_data <- stratify(by = "bbs_usgs",species="Scissor-tailed Flycatcher")
    
data_gam <- prepare_data(stratified_data, 
                              min_year=2009, max_year=2019)
                              
gam_prep<-prepare_model(data_gam,model="gam")

#quick model with too few iterations, we recommend using the defaults, 4 chains, 1000 iterations for both warmup and sampling, and assessing convergence.
gam_mod <- run_model(gam_prep,save_model=FALSE, iter_warmup=500,iter_sampling=100, chains=2)
                               
gam_ind <- generate_indices(gam_mod,regions = c("continent"))
```

```{r GAM_ind, fig.path="./"}
plot_indices(gam_ind)
```

```{r, include=FALSE}
ye_strat<- stratify(by="bbs_usgs",species="Hepatic Tanager")
ye_dat<- prepare_data(ye_strat,min_year=2009, max_year=2019)
ye_prep<-  prepare_model(ye_dat,model = "gamye")
ye_mod<- run_model(ye_prep, chains=3,iter_warmup = 100,iter_sampling = 500,save_model = FALSE)

gamye_ind <- generate_indices(model_output=ye_mod,
                              regions = c("continent"))
gamye_plot = plot_indices(indices = gamye_ind,
                          add_observed_means = TRUE)
```

```{r gamye_plot, fig.path= "./"}
print(gamye_plot)
```

``` {r, include=FALSE}
stratified_data <- stratify(by = "bbs_usgs",species="Scissor-tailed Flycatcher")
    
data_first<- prepare_data(stratified_data, 
                              min_year = 2009, max_year=2019)
                              
first_prep<-prepare_model(data_first,model="first_diff")

#quick model with too few iterations
first_mod <- run_model(first_prep,save_model=FALSE, iter_warmup=500,iter_sampling=100, chains=2)
                               
first_ind <- generate_indices(first_mod,regions = c("continent"))
```

```{r first_ind, fig.path= "./"}
plot_indices(first_ind)   
```

``` {r, include= FALSE}
strat<-stratify(by="bbs_usgs",species="Hepatic Tanager")
d<-prepare_data(strat,min_year=2009, max_year=2019)
m<-prepare_model(d,model = "first_diff",heavy_tailed = TRUE)
mod<-run_model(model_data=m,chains=2,iter_warmup = 500,iter_sampling = 100,save_model = FALSE)


#get heavy tailed plots
heavy_t<-mod %>%
generate_indices(regions="prov_state")
```

```{r poisson_ind, fig.path = "./"}
plot_indices(heavy_t)
```

```{r, include= FALSE}
strat<- stratify(by="bbs_usgs",species = "Hepatic Tanager")
p_dat<-prepare_data(strat, min_year=2009, max_year=2019)
p_mod<-  prepare_model(p_dat, model = "first_diff",use_pois = TRUE)

first_mod<- run_model(p_mod, chains=2,iter_warmup = 500,iter_sampling = 100,save_model = FALSE)

firstdiff_ind <- generate_indices(model_output = first_mod,
                                regions = c("continent","stratum"))
                                
fd_slope_trends_08_18 <- generate_trends(indices = firstdiff_ind,
                                         min_year = 2010,
                                         max_year = 2020,
                                         slope = TRUE)
```

```{r slope_map}
plot_map(fd_slope_trends_08_18,
         slope = TRUE)
```

```{r, include= FALSE}
fd_slope_trends_prob <- generate_trends(indices = firstdiff_ind,
                                             min_year = 2008,
                                             max_year = 2018,
                                             slope = TRUE,
                                             prob_increase = c(0,100))
```

```{r prob_change, fig.path= "./"}
plot_map(fd_slope_trends_prob)
```

```{r, include = FALSE}
#using our downloaded Barn Swallow Gamye example
library(readr)

mod<- bars

    
    #get our stratification
stratification<-stratify(by="bbs_cws","Barn Swallow")
st_comp_regions <- as.data.frame(stratification$meta_strata)
no_barn<- st_comp_regions$bcr[!(st_comp_regions$bcr %in% c(unique(bars$meta_strata$bcr)))]

st_comp_regions$East_West <- ifelse(st_comp_regions$bcr %in% c(7,8,12:14,22:31),"East","West")

#remove regions without Barn Swallows
st_comp_regions$East_West <- ifelse(st_comp_regions$bcr %in% c(no_barn),NA,st_comp_regions$East_West)
ew_indices<-generate_indices(model_output = bars,
                             regions = "East_West",
                             regions_index = st_comp_regions)
plot_indices(ew_indices)
east_west_trends <- generate_trends(indices = ew_indices)


mmm<-load_map(stratify_by = "bbs_cws")
#eastern strata

east<-c(st_comp_regions[st_comp_regions$East_West=="East",][,"strata_name"])

#plot trends by east_west
mmm$ew2<-ifelse(mmm$strata_name %in% c(east),"East","West")


#put the east and west trends into map
e_trend<-as.numeric(filter(east_west_trends$trends,region=="East")[,"trend"])
w_trend<-as.numeric(filter(east_west_trends$trends,region=="West")[,"trend"])

mmm$Trend<-ifelse(mmm$ew2 %in% "East",e_trend,w_trend)
#remove trends when not in barn swallow range
mmm$Trend<-ifelse(mmm$bcr %in% c(no_barn),NA,mmm$Trend)
```

```{r EW_strat, fig.path= "./"}
ggplot()+
  geom_sf(data=mmm,aes(fill=Trend))
```

##bbsBayes2/ Get started

``` {r, indclude=FALSE}
m<-readRDS("C:\\Users\\DalyL\\Downloads\\HETA_bbs_usgs_gamye.rds")
i <- generate_indices(model_output = m)
p<-plot_indices(i)
t <- generate_trends(i)
```

```{r plot_index, fig.path= "./"}
p[["US_AZ_34"]]
```

```{r plot_map, fig.path= "./"}
plot_map(t)
```

##Convergence

```{r, include=FALSE}
heta_gamye <-readRDS("C:\\Users\\DalyL\\Downloads\\HETA_bbs_usgs_gamye.rds")
conv <- get_convergence(heta_gamye)
tconv <- tidyr::pivot_longer(conv, cols = c(ess_bulk, ess_tail, rhat))
post<-as.array(heta_gamye$model_fit$draws())
```

```{r converge,fig.path="./"}
ggplot(data = tconv, aes(x = variable, y = value, colour = variable_type)) +
    geom_point() +
    facet_wrap(~name, scales = "free_y") +
    scale_colour_viridis_d(guide = "none")
```

```{r dense, fig.path= "./"}
mcmc_dens_overlay(post,pars=c("STRATA","phi","retrans_obs","eta","nu","sdste"))
```

##Custom stratification
```{r, include=FALSE}
library(sf)
map <- read_sf("C:\\Users\\DalyL\\Downloads\\WBPHS_stratum_boundaries_2019.shp") %>%
  rename(strata_name = STRAT)
s <- stratify(by = "WBPHS_2019", species = "Canada Jay", strata_custom = map)
p <- prepare_data(s, min_year = 2009, max_year = 2019)
m <- prepare_model(p, model = "first_diff") %>%
  run_model(chains = 2, iter_sampling = 100, iter_warmup = 500, save_model = FALSE)
rindex <- assign_prov_state(map, min_overlap = 0.6, plot = TRUE)
rindex <- mutate(
  rindex, 
  east_west = if_else(as.numeric(strata_name) < 50 | as.numeric(strata_name) > 74,
                      "west", 
                      "east"))
i <- generate_indices(
  m, 
  regions = c("stratum", "country", "prov_state", "east_west"),
  regions_index = rindex)

t <- generate_trends(i)
p <- plot_indices(i)
names(p)

```

```{r rindex, fig.path="./"}
ggplot(rindex) +
  geom_sf(data = load_map(type = "North America")) +
  geom_sf() +
  geom_sf_text(aes(label = strata_name))
```

```{r rindex_2, fig.path= "./"}
ggplot(data = rindex) +
  geom_sf(data = load_map(type = "North America")) +
  geom_sf(data = rindex, aes(fill = east_west), alpha = 0.5)
```

``` {r ew_ind, fig.path="./" }
p[["east"]] + p[["west"]]
```

```{r geofacet_ew, fig.path= "./"}
plot_geofacet(i, trends = t, multiple = TRUE)
```
##Models: first-difference
```{r, include=FALSE }
s <- stratify(by = "bbs_cws", sample = TRUE)
p <- prepare_data(s,min_year=2009, max_year=2019)
md <- prepare_model(p, model = "first_diff", model_variant = "hier")
m <- run_model(md, iter_sampling = 100, iter_warmup = 500, chains = 2,save_model = FALSE)
i <- generate_indices(model_output = m,
                      regions = c("continent",
                                  "country",
                                  "prov_state",
                                  "stratum"))
p <- plot_indices(i, add_observed_means = TRUE)
t <- generate_trends(indices = i)
```

```{r first_index, fig.path="./", fig.width = 16, fig.asp = length(plot)/3*3}
patchwork::wrap_plots(p, ncol = 3)
```

```{r first_map, fig.path= "./"}
plot_map(trends = t)
```

```{r first_geo, fig.path= "./", fig.width = 16, fig.asp = length(plot)/3*3}
plot_geofacet(indices = i, trends = t)
```

##First-difference non-hierarchical

```{r, include=FALSE}
s <- stratify(by = "bbs_cws", species="Hepatic Tanager")
p <- prepare_data(s, min_year=2009, max_year=2019)
md <- prepare_model(p, model = "first_diff", model_variant = "nonhier")
m <- run_model(md, iter_sampling = 100, iter_warmup = 500, chains = 2,save_model = FALSE)
i <- generate_indices(model_output = m,
                      regions = c("continent",
                                  "country",
                                  "prov_state",
                                  "stratum"))
p <- plot_indices(i, add_observed_means = TRUE)
t <- generate_trends(indices = i)
```

```{r first_nonhier-1.png, fig.path= "./", fig.width = 16, fig.asp = length(plot)/3*3}
patchwork::wrap_plots(p, ncol = 3)
```

```{r first_nonhier_trend, fig.path="./"}
plot_map(trends = t)
```

```{r first_nonhier_geo, fig.path= "./", fig.width = 16, fig.asp = length(plot)/3*3}
plot_geofacet(indices = i, trends = t)
```

##First-difference spatial
```{r include=FALSE}
s <- stratify(by = "bbs_usgs", species="Hepatic Tanager")
p <- prepare_data(s, min_year=2009, max_year=2019)
map <- load_map("bbs_cws")
n <- prepare_spatial(p, map)
md <- prepare_model(n, model = "first_diff", model_variant = "spatial")
m <- run_model(md, iter_sampling = 100, iter_warmup = 500, chains = 2,save_model = FALSE)
i <- generate_indices(model_output = m,
                      regions = c("continent",
                                  "country",
                                  "prov_state",
                                  "stratum"))
p <- plot_indices(i, add_observed_means = TRUE)
t <- generate_trends(indices = i)

```

```{r usgs_strata, fig.path="./"}
ggplot(map, aes(fill = strata_name)) +
  geom_sf(show.legend = FALSE)
```

```{r first_spatial_index, fig.path="./", fig.width = 16, fig.asp = length(plot)/3*3}
patchwork::wrap_plots(p, ncol = 3)
```

```{r first_spatial_trend, fig.path="./", fig.width = 16, fig.asp = length(plot)/3*3}
plot_map(trends = t)
```

```{r first_spatial_geo,fig.path="./", fig.width = 16, fig.asp = length(plot)/3*3}
plot_geofacet(indices = i, trends = t)
```

##GAM hier
```{r, include=FALSE}
s <- stratify(by = "bbs_cws", species="Hepatic Tanager")
p <- prepare_data(s, min_year=2009, max_year=2019)
md <- prepare_model(p, model = "gam", model_variant = "hier")
m <- run_model(md, iter_sampling = 100, iter_warmup = 500, chains = 2,save_model = FALSE)
i <- generate_indices(model_output = m,
                      regions = c("continent",
                                  "country",
                                  "prov_state",
                                  "stratum"))

p <- plot_indices(i, add_observed_means = TRUE)
t <- generate_trends(indices = i)

```

```{r gam_index, fig.path="./", fig.width = 16, fig.asp = length(plot)/3*3}
patchwork::wrap_plots(p, ncol = 3)
```

```{r gam_trend}
plot_map(trends = t)
```

```{r gam_geo,fig.path="./", fig.width = 16, fig.asp = length(plot)/3*3 }
plot_geofacet(indices = i, trends = t)
```

##GAM spatial
```{r, include=FALSE}
s <- stratify(by = "bbs_cws", species= "Hepatic Tanager")
p <- prepare_data(s, min_year=2009, max_year=2019)
map <- load_map("bbs_cws")
n <- prepare_spatial(p, map)
md <- prepare_model(n, model = "gam", model_variant = "spatial")
m <- run_model(md, iter_sampling = 100, iter_warmup = 500, chains = 2,save_model = FALSE)
i <- generate_indices(model_output = m,
                      regions = c("continent",
                                  "country",
                                  "prov_state",
                                  "stratum"))
p <- plot_indices(i, add_observed_means = TRUE)
t <- generate_trends(indices = i)

```

```{r gam_spatial_strata, fig.path="./"}
ggplot(map, aes(fill = strata_name)) +
  geom_sf(show.legend = FALSE)
```

```{r gam_spatial_index,fig.path= "./" ,fig.width = 16, fig.asp = length(plot)/3*3 }
patchwork::wrap_plots(p, ncol = 3)
```

```{r gam_spatial_trend, fig.path="./"}
plot_map(trends = t)
```

```{r gam_spatial_geo, fig.path= "./" ,fig.width = 16, fig.asp = length(plot)/3*3}
plot_geofacet(indices = i, trends = t)
```

##GAMYE hier
```{r, include=FALSE}
s <- stratify(by = "bbs_cws", species= "Hepatic Tanager")
p <- prepare_data(s, min_year=2009, max_year=2019)
md <- prepare_model(p, model = "gamye", model_variant = "hier")
m <- run_model(md, iter_sampling = 10, iter_warmup = 10, chains = 2,save_model = FALSE)
i <- generate_indices(model_output = m,
                      regions = c("continent",
                                  "country",
                                  "prov_state",
                                  "stratum"))
p <- plot_indices(i, add_observed_means = TRUE)
t <- generate_trends(indices = i)

```

```{r gamye_index, fig.path= "./" ,fig.width = 16, fig.asp = length(plot)/3*3 }
patchwork::wrap_plots(p, ncol = 3)
```

```{r gamye_trend, fig.path= "./" ,fig.width = 16, fig.asp = length(plot)/3*3 }
plot_map(trends = t)
```

```{r gamye_geo, fig.path= "./" ,fig.width = 16, fig.asp = length(plot)/3*3}
plot_geofacet(indices = i, trends = t)
```

##GAMYE spatial
```{r, include=FALSE}
s <- stratify(by = "bbs_usgs", species= "Hepatic Tanager")
p <- prepare_data(s, min_year=2009, max_year=2019)
map <- load_map("bbs_usgs")
n <- prepare_spatial(p, map)
md <- prepare_model(n, model = "gamye", model_variant = "spatial")
m <- run_model(md, iter_sampling = 10, iter_warmup = 10, chains = 2,save_model = FALSE)
i <- generate_indices(model_output = m,
                      regions = c("continent",
                                  "country",
                                  "prov_state",
                                  "stratum"))

p <- plot_indices(i, add_observed_means = TRUE)
t <- generate_trends(indices = i)

```

```{r gamye_spatial_index,fig.path= "./" ,fig.width = 16, fig.asp = length(plot)/3*3}
patchwork::wrap_plots(p, ncol = 3)
```

```{r gamye_spatial_trend}
plot_map(trends = t)
```

```{r gamye_spatial_geo,fig.path= "./" ,fig.width = 16, fig.asp = length(plot)/3*3}
plot_geofacet(indices = i, trends = t)
```

```{r, include=FALSE}
s <- stratify(by = "bbs_cws", sample = TRUE)
p <- prepare_data(s, min_year= 2009, max_year=2019)
md <- prepare_model(p, model = "slope", model_variant = "hier")
m <- run_model(md, iter_sampling = 100, iter_warmup = 500, chains = 2,save_model = FALSE)
i <- generate_indices(model_output = m,
                      regions = c("continent",
                                  "country",
                                  "prov_state",
                                  "stratum"))
p <- plot_indices(i, add_observed_means = TRUE)
t <- generate_trends(indices = i)

```

```{r slope_index,fig.path= "./" ,fig.width = 16, fig.asp = length(plot)/3*3}
patchwork::wrap_plots(p, ncol = 3)
```

```{r slope_trend, fig.path= "./"}
plot_map(trends = t)
```

```{r slope_geo,fig.path= "./" ,fig.width = 16, fig.asp = length(plot)/3*3}
plot_geofacet(indices = i, trends = t)
```

##slope spatial
```{r, include=FALSE}
s <- stratify(by = "bbs_usgs", species= "Hepatic Tanager")
p <- prepare_data(s, min_year=2009, max_year=2019)
n <- prepare_spatial(p, map)
md <- prepare_model(n, model = "slope", model_variant = "spatial")
m <- run_model(md, iter_sampling = 100, iter_warmup = 500, chains = 2,save_model = FALSE)
i <- generate_indices(model_output = m,
                      regions = c("continent",
                                  "country",
                                  "prov_state",
                                  "stratum"))
p <- plot_indices(i, add_observed_means = TRUE)
t <- generate_trends(indices = i)

```

```{r slope_spatial_index,fig.path= "./" ,fig.width = 16, fig.asp = length(plot)/3*3}
patchwork::wrap_plots(p, ncol = 3)
```

```{r slope_spatial_trend}
plot_map(trends = t)
```

```{r slope_spatial_geo, fig.path= "./" ,fig.width = 16, fig.asp = length(plot)/3*3}
plot_geofacet(indices = i, trends = t)
```

##stratification
```{r cws_map, fig.path="./"}
ggplot(data = load_map("bbs_cws"), aes(fill = strata_name)) +
  geom_sf() +
  scale_fill_viridis_d(guide = "none")
```

```{r, inlcude=FALSE}
library(sf)
library(dplyr)
library(patchwork)
s <- stratify(by = "bbs_usgs", species = "Canada Jay")
my_cws <- filter(bbs_strata[["bbs_cws"]], country == "Canada")
s <- stratify(by = "bbs_cws", species = "Canada Jay", strata_custom = my_cws)

```

```{r meta_strata, echo=TRUE,fig.path="./"}
print(s[["meta_strata"]], n=Inf)
```

```{r, include=FALSE}
map <- read_sf("C:\\Users\\DalyL\\Downloads\\WBPHS_stratum_boundaries_2019.shp")
```

```{r custom_strata, fig.path="./"}
ggplot(map, aes(fill = factor(STRAT))) + 
  geom_sf() +
  scale_fill_viridis_d(guide = "none")
```

```{r, include=FALSE}
map <- rename(map, strata_name = STRAT)
s <- stratify(by = "WBPHS_2019", species = "Canada Jay", strata_custom = map)
r <- s[["routes_strata"]] %>%
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326)
```

```{r meta, fig.path= "./"}
s[["meta_data"]]
```

```{r route_meta, fig.path="./"}
s[["routes_strata"]]
```

```{r route_names, fig.path= "./"}
ggplot() +
  geom_sf(data = map, aes(fill = factor(strata_name)), alpha = 0.3) +
  geom_sf(data = r, aes(colour = factor(strata_name)), size = 1) +
  scale_fill_viridis_d(aesthetics = c("colour", "fill"), guide = "none")
```

```{r, include=FALSE }
s <- stratify(by = "WBPHS_2019", species = "Canada Jay", strata_custom = map,
              return_omitted = TRUE)
omitted <- st_as_sf(s[["routes_omitted"]], coords = c("longitude", "latitude"), 
                    crs= 4326)
bbs_routes <- load_bbs_data()[["routes"]] %>%
  st_as_sf(coords = c("longitude", "latitude"), crs= 4326)
```

```{r routes_omitted, fig.path="./"}
s[["routes_omitted"]]
```

```{r omitted_map, fig.path= "./"}
ggplot() +
  geom_sf(data = map, aes(fill = factor(strata_name)), alpha = 0.3) +
  geom_sf(data = r, aes(colour = factor(strata_name)), size = 1, alpha = 0.5) +
  geom_sf(data = omitted, size = 0.75, alpha = 0.5) +
  scale_fill_viridis_d(aesthetics = c("colour", "fill"), guide = "none")
```

```{r route_map, fig.path="./"}
ggplot() +
  geom_sf(data = map, aes(fill = factor(strata_name)), alpha = 0.3) +
  geom_sf(data = r, aes(colour = factor(strata_name)), size = 1) +
  geom_sf(data = bbs_routes, size = 0.5) +
  scale_fill_viridis_d(aesthetics = c("colour", "fill"), guide = "none") 
```
## stratification- custom stratification
```{r, include=FALSE}
map <- load_map("bbs_cws")
new_map <- map %>%
  filter(country_code == "CA", !prov_state %in% c("NT", "NU", "YT")) %>%
  st_transform(4326)%>%
  st_make_valid()
west <- st_crop(new_map, xmin = -140, ymin = 42, xmax = -95, ymax = 68) %>%
  mutate(strata_name = "west")
east <- st_crop(new_map, xmin = -95, ymin = 42, xmax = -52, ymax = 68) %>%
  mutate(strata_name = "east")
new_strata <- bind_rows(west, east) %>%
  st_transform(st_crs(map))
```

```{r og_crs, fig.path="./"}
ggplot() +
  geom_sf(data = map) +
  geom_sf(data = new_strata, aes(fill = strata_name), alpha = 1)
```

```{r, include=FALSE}
s <- stratify(by = "canada_ew", species = "Canada Jay", 
              strata_custom = new_strata)

s$meta_data
routes <- s$routes_strata %>%
  st_as_sf(coords = c("longitude", "latitude"), crs = 4326)
```

```{r new_strata, fig.path="./"}
ggplot() +
  geom_sf(data = new_strata, aes(fill = strata_name), alpha = 1) +
  geom_sf(data = routes, aes(shape = strata_name))
```
```

